version: 0.2

os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes


hooks:
  AfterInstall: 
    - location: scripts/restart_apache.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/post_deploy.sh
      runas: ubuntu    